# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/sale

    branches:
      only:
        - master

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            ls
            yarn
            ls

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Building
          command: |
            yarn build
            ls

      - save_cache:
          paths:
            - build
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

      - add_ssh_keys:
          fingerprints:
            - '07:e7:6a:a6:80:4e:d0:b5:f0:80:cc:b3:2c:2f:37:4a'

      - run:
          name: upload
          command: |
            ls
            ssh -i -p 29797 root@104.224.131.116
            ls
            pwd
            sudo scp -i ~/.ssh/id_rsa_07e76aa6804ed0b5f080ccb32c2f374a -P 29797 -r /build/* root@104.224.131.116:/joey/front/sale
            # scp -r -P 29797 ./build/* root@104.224.131.116:/joey/front/sale

#   deploy:
#     working_directory: ~/sale
#     docker:
#       - image: circleci/node:lts

#     steps:
#       # show current branch
#       - run:
#           name: Show current branch
#           command: echo ${CIRCLE_BRANCH}

#       - restore_cache:
#           key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

#       - add_ssh_keys:
#           fingerprints:
#             - '07:e7:6a:a6:80:4e:d0:b5:f0:80:cc:b3:2c:2f:37:4a'

#       # - run:
#       #     name: upload
#       #     command: |
#       #       scp -r -P 29797 ./build/* root@104.224.131.116:/joey/front/sale

#       - run:
#           name: scp build
#           command: |
#             ls
#             sudo scp -i ~/.ssh/id_rsa_07e76aa6804ed0b5f080ccb32c2f374a' -P 29797 -r /build/* root@104.224.131.116:/joey/front/sale

# workflows:
#   version: 2
#   build-and-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only:
#                 - master
