# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/sale

    branches:
      only:
        - master

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - add_ssh_keys:
          fingerprints:
            - '07:e7:6a:a6:80:4e:d0:b5:f0:80:cc:b3:2c:2f:37:4a'

      - run: echo '[104.224.131.116]:29797 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBA8w8cGglsCrHirTw1SUC1UP9+f/RHHtLvjjc+SMO0o66wUqiiuojwGI5uYyFAFjCyS4A+n+D6oAVO2o3r2rr6M=' >> ~/.ssh/known_hosts

      - run:
          command: |
            yarn
            yarn build
            pwd
            ls
            scp -r -P 29797 ./build/* root@104.224.131.116:/joey/front/sale

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
